// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthGoogle struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Sub        string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type CalendarAccount struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	Provider   string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Customer struct {
	ID        uuid.UUID
	Name      string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MagicLink struct {
	ID         uuid.UUID
	CustomerID uuid.UUID
	TokenHash  string
	ExpiresAt  time.Time
	UsedAt     sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Valarm struct {
	ID          uuid.UUID
	EventUid    string
	Action      string
	Trigger     string
	Description sql.NullString
	Summary     sql.NullString
	Duration    sql.NullString
	Repeat      sql.NullInt32
	Attendees   pqtype.NullRawMessage
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Vcalendar struct {
	Uid         string
	AccountID   uuid.UUID
	Prodid      string
	Version     string
	Calscale    sql.NullString
	DisplayName string
	Description sql.NullString
	Color       sql.NullString
	Timezone    sql.NullString
	Sequence    sql.NullInt32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Vevent struct {
	Uid            string
	CalendarUid    string
	Dtstamp        time.Time
	Dtstart        time.Time
	Dtend          sql.NullTime
	Duration       sql.NullString
	Summary        string
	Description    sql.NullString
	Location       sql.NullString
	Status         sql.NullString
	Classification sql.NullString
	Transp         sql.NullString
	Rrule          sql.NullString
	Rdate          pqtype.NullRawMessage
	Exdate         pqtype.NullRawMessage
	Sequence       sql.NullInt32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type VeventException struct {
	ID           uuid.UUID
	EventUid     string
	RecurrenceID time.Time
	Summary      sql.NullString
	Description  sql.NullString
	Location     sql.NullString
	Dtstart      sql.NullTime
	Dtend        sql.NullTime
	Status       sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
