workflows:
  jadwal-release:
    name: Jadwal Release
    working_directory: mishkat
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.jadwal.mishkat
      vars:
        BUNDLE_ID: app.jadwal.mishkat
        XCODE_WORKSPACE: Mishkat.xcodeproj
        XCODE_SCHEME: Mishkat
      xcode: 16.0
    scripts:
      - name: Run the hack for making next step work hopefully
        script: gem update xcodeproj
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --project "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    integrations:
      app_store_connect: Fadi AlKhalaf Cloudmagic
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - trusted
