services:
  traefik:
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"

  falak:
    image: ghcr.io/jadwalapp/symmetrical-spoon/falak:main
