services:
  traefik:
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--log.level=DEBUG"
      - "--entryPoints.web.address=:80"
    ports:
      - "8080:8080"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=web"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/certs:/certs:ro"

  postgresdb:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  falak:
    build:
      context: ./falak
      dockerfile: "Dockerfile"
      target: dev
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=symmetrical-spoon_web"
      - "traefik.http.routers.falak.rule=Host(`${FALAK_HOST}`)"
      - "traefik.http.routers.falak.entrypoints=web"
      - "traefik.http.services.falak.loadbalancer.server.port=${FALAK_PORT}"
      - "traefik.http.services.falak.loadbalancer.server.scheme=h2c"
    ports:
      - "50064:50064"
    develop:
      watch:
        - path: ./falak
          target: /falak
          action: sync+restart
          ignore:
            - go.sum
        - path: ./falak/go.sum
          action: rebuild

  website:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`${WEBSITE_HOST}`)"
      - "traefik.http.routers.website.entrypoints=web"
      - "traefik.http.services.website.loadbalancer.server.port=8080"

  grafana:
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=symmetrical-spoon_web"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOST}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  loki:
    ports:
      - "3100:3100"

  baikal:
    ports:
      - 3322:80
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=symmetrical-spoon_web"
      - "traefik.http.routers.baikal.rule=Host(`${BAIKAL_HOST}`)"
      - "traefik.http.routers.baikal.entrypoints=web"
      - "traefik.http.services.baikal.loadbalancer.server.port=80"

  wasapp:
    ports:
      - 3000:3000

  rabbitmq:
    ports:
      - "5672:5672" # AMQP protocol port
      - "15672:15672" # Management UI port

  # extra stuff - only local
  plantuml:
    image: plantuml/plantuml-server:jetty
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=symmetrical-spoon_web"
      - "traefik.http.routers.plantuml.rule=Host(`plantuml.localhost`)"
      - "traefik.http.routers.plantuml.entrypoints=web"
      - "traefik.http.services.plantuml.loadbalancer.server.port=8080"
    networks:
      - web
