FROM golang:1.23.2 AS builder
WORKDIR /falak
COPY ./falak .
RUN CGO_ENABLED=0 GOOS=linux go build -o main cmd/main.go

FROM scratch
COPY --from=builder /falak/main /main
COPY ./falak/grpc.env.example /grpc.env
COPY ./falak/pkg/store/migrations pkg/store/migrations
CMD [ "/main" ]