@startchen Calendar

entity CalendarAccount {
  Id
  Name
}

entity Calendar {
  Id
  Name
  StartDate
  EndDate
  Color
}

entity CalendarEvent {
  Id
  EventTitle
  Location
  IsAllDay
  StartDate
  EndDate
}

relationship OwnsCalendars {
}
OwnsCalendars =1= CalendarAccount
OwnsCalendars =N= Calendar

relationship ContainsEvents {
}
ContainsEvents =1= Calendar
ContainsEvents =N= CalendarEvent

@endchen