version: "3"
tasks:
  new-mig:
    desc: Create a new migration.
    cmds:
      - migrate create -dir pkg/store/migrations/ -ext sql --seq {{.MIG_NAME}}
    requires:
      vars: [MIG_NAME]

  sqlc-gen:
    desc: Generate store code using sqlc.
    cmds:
      - sqlc generate

  test:
    desc: Run tests for all packages.
    cmds:
      - go test ./...

  test-cov:
    desc: Run tests for all packages and generate coverage report.
    cmds:
      - go test -coverpkg=./... -coverprofile=coverage.out ./...

  test-cov-show:
    desc: Run tests for all packages and generate coverage report.
    deps:
      - test-cov
    cmds:
      - go tool cover -html=coverage.out

  run:
    desc: Run the server.
    cmds:
      - go run cmd/main.go

  mig-up:
    desc: Run all migrations.
    cmds:
      - migrate -path pkg/store/migrations/ -database "postgresql://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode={{.DB_SSL_MODE}}" -verbose up 1
    vars:
      DB_USER:
        sh: grep -w "POSTGRES_USER" ../.env | cut -d "=" -f2-
      DB_PASSWORD:
        sh: grep -w "POSTGRES_PASSWORD" ../.env | cut -d "=" -f2-
      DB_HOST: localhost
      DB_PORT:
        sh: grep -w "POSTGRES_PORT" ../.env | cut -d "=" -f2-
      DB_NAME:
        sh: grep -w "POSTGRES_DB" ../.env | cut -d "=" -f2-
      DB_SSL_MODE: disable

  mig-down:
    desc: Rollback all migrations.
    cmds:
      - migrate -path pkg/store/migrations/ -database "postgresql://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode={{.DB_SSL_MODE}}" -verbose down 1
    vars:
      DB_USER:
        sh: grep -w "POSTGRES_USER" ../.env | cut -d "=" -f2-
      DB_PASSWORD:
        sh: grep -w "POSTGRES_PASSWORD" ../.env | cut -d "=" -f2-
      DB_HOST: localhost
      DB_PORT:
        sh: grep -w "POSTGRES_PORT" ../.env | cut -d "=" -f2-
      DB_NAME:
        sh: grep -w "POSTGRES_DB" ../.env | cut -d "=" -f2-
      DB_SSL_MODE: disable
  
  gen-email-temps:
    desc: Generate email templates.
    cmds:
      - mkdir -p pkg/email/templates/ar
      - mkdir -p pkg/email/templates/en

      - mjml pkg/email/templates/mjml/ar/magic-link.mjml -o pkg/email/templates/ar/magic-link.html
      - mjml pkg/email/templates/mjml/en/magic-link.mjml -o pkg/email/templates/en/magic-link.html

      - mjml pkg/email/templates/mjml/ar/welcome.mjml -o pkg/email/templates/ar/welcome.html
      - mjml pkg/email/templates/mjml/en/welcome.mjml -o pkg/email/templates/en/welcome.html