  name: Deploy

  on:
    workflow_run:
      workflows: ["Build and Push Falak Image"]
      types:
        - completed
    workflow_dispatch:

  jobs:
    deploy:
      runs-on: ubuntu-latest
      if: |
        github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.1
        
        - name: Run whoami through ssh :D
          uses: appleboy/ssh-action@v1.1.0
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: deploy
            key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
            port: 22
            script: whoami
        
        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
            echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_jadwal_app
            chmod 600 ~/.ssh/deploy_jadwal_app

        - name: Deploy docker compose using docker context
          run: |
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/deploy_jadwal_app
            
            docker context create deploy --docker host=ssh://deploy@${{ secrets.DEPLOY_HOST }}
            docker context use deploy
            cd symmetrical-spoon
            git pull
            docker compose -f comopose.yaml -f compose.prod.yaml pull
            docker compose -f comopose.yaml -f compose.prod.yaml up -d
