  name: Deploy

  on:
    workflow_run:
      workflows: ["Build and Push Falak Image", "Build and Push Website Image", "Build and Push Wasapp Image"]
      types:
        - completed
    workflow_dispatch:

  jobs:
    deploy:
      runs-on: ubuntu-latest
      if: |
        github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
      steps:
        - name: Checkout code
          uses: actions/checkout@v4.2.1
        
        - name: Deploy the new stuff :D
          uses: appleboy/ssh-action@v1.1.0
          with:
            host: ${{ secrets.DEPLOY_HOST }}
            username: deploy
            key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
            port: 22
            script: |
              eval "$(ssh-agent -s)"
              ssh-add ~/.ssh/deploy_jadwal_app

              cd symmetrical-spoon
              git pull
              docker compose -f compose.yaml -f compose.prod.yaml pull
              docker compose -f compose.yaml -f compose.prod.yaml up -d --remove-orphans
