name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Falak Image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1

    - name: Setup SSH key and start ssh-agent
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        SSH_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts
        eval $(ssh-agent -s)
        echo "$SSH_PASSPHRASE" | SSH_ASKPASS="/bin/echo" ssh-add ~/.ssh/id_ed25519

    - name: Test SSH connection
      run: |
        ssh -v deploy@${{ secrets.DEPLOY_HOST }} 'echo "SSH connection successful"'

    - name: Create environment files
      run: |
        echo "${{ secrets.FALAK_ENV }}" > falak/grpc.env
        echo "${{ secrets.MAIN_ENV }}" > .env

    - name: Create Docker context
      run: |
        docker context create deploy --docker "host=ssh://deploy@${{ secrets.DEPLOY_HOST }}" --description "Remote Docker host" -v
        docker context ls
        docker context use deploy
        docker context inspect deploy

    - name: Check remote Docker version
      run: |
        docker --context deploy version

    - name: Login to GitHub Container Registry
      run: |
        echo "${{ secrets.GHCR_PAT }}" | docker --context deploy login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Deploy
      run: |
        docker --context deploy info
        docker --context deploy compose -f compose.yaml -f compose.prod.yaml config
        docker --context deploy compose -f compose.yaml -f compose.prod.yaml pull --verbose
        docker --context deploy compose -f compose.yaml -f compose.prod.yaml up -d --verbose

    - name: Cleanup
      if: always()
      run: |
        docker --context deploy logout ghcr.io
        rm -rf ~/.ssh
        ssh-agent -k