name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push Falak Image"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts

    - name: Create Docker context
      run: |
        docker context create deploy --docker "host=ssh://deploy@${{ secrets.DEPLOY_HOST }}"

    - name: Deploy
      run: |
        docker --context deploy compose -f compose.yaml -f compose.prod.yaml pull
        docker --context deploy compose -f compose.yaml -f compose.prod.yaml up -d

    - name: Cleanup
      run: |
        rm -rf ~/.ssh